### ISSUE TITLE
requirements.txt need update

### ISSUE THREAD

**Issue by AlexXiong97** [b-mueller/mythril#18]
[in setup.py](https://github.com/b-mueller/mythril/blob/1a1d5123ff1a4d0f4dd4b0389b52699f63c09035/setup.py#L259), `laser-ethereum>=0.1.7` is specified, while [in requirements.txt](https://github.com/b-mueller/mythril/blob/1a1d5123ff1a4d0f4dd4b0389b52699f63c09035/requirements.txt#L5), the version is `0.1.4`.

Please pip freeze and update the latest pip list, 
(Plus, the actual package list should be much longer since the dependency list of mythril package is huge.)
Thanks!

**Comment by b-mueller** [comment]
Thanks, I'm currently working on a bigger update, will clean this up with the next merge into master.

**Comment by b-mueller** [comment]
I updated the laser-ethereum version and tried to add any non-standard packages I have installed. Let me know if something's still missing.
