### ISSUE TITLE
Provide recent or own signatures.json file

### ISSUE THREAD

**Issue by ice09** [b-mueller/mythril#29]
Would be great to be able to provide a path for a more recent or manually modified `signature.json` file without having to rebuild the application.

**Comment by b-mueller** [comment]
That's a great suggestion & something I already had in mind. Would you like to do a pull request? Otherwise, I'll add it in the next days.

**Comment by b-mueller** [comment]
As of 0.8.18, `signatures.json` is now located in `~/.mythril`.
