### ISSUE TITLE
Intsall failed

### ISSUE THREAD

**Issue by tjayrush** [b-mueller/mythril#3]
I tried to install with this `pip install mythril` and got this result:

@./mythril:jrush>$ pip install mythril
Collecting mythril
  Downloading mythril-0.1.6.tar.gz
Collecting ethereum==2.0.4 (from mythril)
  Downloading ethereum-2.0.4.tar.gz (139kB)
    100% |████████████████████████████████| 143kB 2.5MB/s
Collecting repoze.lru (from ethereum==2.0.4->mythril)
  Downloading repoze.lru-0.7.tar.gz
Requirement already satisfied: PyYAML in /usr/local/lib/python2.7/site-packages (from ethereum==2.0.4->mythril)
Collecting pbkdf2 (from ethereum==2.0.4->mythril)
  Downloading pbkdf2-1.3.tar.gz
Collecting bitcoin (from ethereum==2.0.4->mythril)
  Downloading bitcoin-1.1.42.tar.gz
Collecting pycryptodome>=3.3.1 (from ethereum==2.0.4->mythril)
  Downloading pycryptodome-3.4.7.tar.gz (6.5MB)
    100% |████████████████████████████████| 6.5MB 194kB/s
Collecting scrypt (from ethereum==2.0.4->mythril)
  Downloading scrypt-0.8.0-cp27-cp27m-macosx_10_11_x86_64.whl
Collecting pysha3>=1.0.1 (from ethereum==2.0.4->mythril)
  Downloading pysha3-1.0.2.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 1.4MB/s
Collecting rlp>=0.4.7 (from ethereum==2.0.4->mythril)
  Downloading rlp-0.6.0.tar.gz
Collecting pyethash (from ethereum==2.0.4->mythril)
  Downloading pyethash-0.1.27.tar.gz
Building wheels for collected packages: mythril, ethereum, repoze.lru, pbkdf2, bitcoin, pycryptodome, pysha3, rlp, pyethash
  Running setup.py bdist_wheel for mythril ... error
  Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/20/42k6jhsj325_yl419srn69280000gn/T/pip-build-l7NqpX/mythril/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/20/42k6jhsj325_yl419srn69280000gn/T/tmpPIUqU8pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/ether
  copying ether/__init__.py -> build/lib/ether
  copying ether/asm.py -> build/lib/ether
  copying ether/evm.py -> build/lib/ether
  copying ether/util.py -> build/lib/ether
  creating build/lib/rpc
  copying rpc/__init__.py -> build/lib/rpc
  copying rpc/client.py -> build/lib/rpc
  copying rpc/constants.py -> build/lib/rpc
  copying rpc/exceptions.py -> build/lib/rpc
  copying rpc/utils.py -> build/lib/rpc
  running build_scripts
  creating build/scripts-2.7
  copying and adjusting mythril -> build/scripts-2.7
  changing mode of build/scripts-2.7/mythril from 644 to 755
  installing to build/bdist.macosx-10.12-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-10.12-x86_64
  creating build/bdist.macosx-10.12-x86_64/wheel
  creating build/bdist.macosx-10.12-x86_64/wheel/ether
  copying build/lib/ether/__init__.py -> build/bdist.macosx-10.12-x86_64/wheel/ether
  copying build/lib/ether/asm.py -> build/bdist.macosx-10.12-x86_64/wheel/ether
  copying build/lib/ether/evm.py -> build/bdist.macosx-10.12-x86_64/wheel/ether
  copying build/lib/ether/util.py -> build/bdist.macosx-10.12-x86_64/wheel/ether
  creating build/bdist.macosx-10.12-x86_64/wheel/rpc
  copying build/lib/rpc/__init__.py -> build/bdist.macosx-10.12-x86_64/wheel/rpc
  copying build/lib/rpc/client.py -> build/bdist.macosx-10.12-x86_64/wheel/rpc
  copying build/lib/rpc/constants.py -> build/bdist.macosx-10.12-x86_64/wheel/rpc
  copying build/lib/rpc/exceptions.py -> build/bdist.macosx-10.12-x86_64/wheel/rpc
  copying build/lib/rpc/utils.py -> build/bdist.macosx-10.12-x86_64/wheel/rpc
  running install_egg_info
  running egg_info
  writing requirements to mythril.egg-info/requires.txt
  writing mythril.egg-info/PKG-INFO
  writing top-level names to mythril.egg-info/top_level.txt
  writing dependency_links to mythril.egg-info/dependency_links.txt
  reading manifest file 'mythril.egg-info/SOURCES.txt'
  writing manifest file 'mythril.egg-info/SOURCES.txt'
  Copying mythril.egg-info to build/bdist.macosx-10.12-x86_64/wheel/mythril-0.1.6-py2.7.egg-info
  running install_scripts
  creating build/bdist.macosx-10.12-x86_64/wheel/mythril-0.1.6.data
  creating build/bdist.macosx-10.12-x86_64/wheel/mythril-0.1.6.data/scripts
  copying build/scripts-2.7/mythril -> build/bdist.macosx-10.12-x86_64/wheel/mythril-0.1.6.data/scripts
  changing mode of build/bdist.macosx-10.12-x86_64/wheel/mythril-0.1.6.data/scripts/mythril to 755
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/20/42k6jhsj325_yl419srn69280000gn/T/pip-build-l7NqpX/mythril/setup.py", line 163, in <module>
      scripts=['mythril']
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 232, in run
      self.distinfo_dir)
    File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 399, in egg2dist
      distribution=self.distribution)
    File "/usr/local/lib/python2.7/site-packages/wheel/metadata.py", line 129, in pkginfo_to_dict
      payload = payload.decode('utf-8')
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
      return codecs.utf_8_decode(input, errors, True)
  UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 1757: invalid start byte

  ----------------------------------------
  Failed building wheel for mythril
  Running setup.py clean for mythril
  Running setup.py bdist_wheel for ethereum ... done
  Stored in directory: /Users/jrush/Library/Caches/pip/wheels/ff/ee/fd/d155ede9dba88b679720c87975f2eeab21befc43da2b7b075e
  Running setup.py bdist_wheel for repoze.lru ... done
  Stored in directory: /Users/jrush/Library/Caches/pip/wheels/f2/f9/a7/f5c72abc5a083f4ef4b2e3eb4c4721300cf0735ac06958a2e7
  Running setup.py bdist_wheel for pbkdf2 ... done
  Stored in directory: /Users/jrush/Library/Caches/pip/wheels/4a/1a/64/4dd31676e41ecf2917a870a96a874c860508d3b5d1b440b52b
  Running setup.py bdist_wheel for bitcoin ... done
  Stored in directory: /Users/jrush/Library/Caches/pip/wheels/15/d9/46/0029939110ce681cbcb1b94b8952f475eb3562e65cd99d311f
  Running setup.py bdist_wheel for pycryptodome ... done
  Stored in directory: /Users/jrush/Library/Caches/pip/wheels/f7/cb/16/1ed6dc50b92888af9051bda6f59f335dfd966a1ce5edd8a4af
  Running setup.py bdist_wheel for pysha3 ... done
  Stored in directory: /Users/jrush/Library/Caches/pip/wheels/00/06/c3/ad27a11d795e4400ebaf0242a5b316820f33b6633e19435ee5
  Running setup.py bdist_wheel for rlp ... done
  Stored in directory: /Users/jrush/Library/Caches/pip/wheels/00/27/d0/354150ba37723f2469f6eb69b07ccdce983a3cd572584d9e8c
  Running setup.py bdist_wheel for pyethash ... done
  Stored in directory: /Users/jrush/Library/Caches/pip/wheels/4c/a1/67/af345dfb35e42a2b0f9d0a5d7b5996ac5959a1b05e286664b0
Successfully built ethereum repoze.lru pbkdf2 bitcoin pycryptodome pysha3 rlp pyethash
Failed to build mythril
Installing collected packages: repoze.lru, pbkdf2, bitcoin, pycryptodome, scrypt, pysha3, rlp, pyethash, ethereum, mythril
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/LICENSE'

And the myth command line toold does not install.

**Comment by b-mueller** [comment]
Try Python 3.5!

**Comment by tjayrush** [comment]
Instructions?

**Comment by b-mueller** [comment]
- [PyEnv](https://github.com/pyenv/pyenv)
