### ISSUE TITLE
Ability to point analysis on a directory with multiple contracts

### ISSUE THREAD

**Issue by ajsantander** [b-mueller/mythril#32]
Atm, you have to specify analysis on a file or a list of files (file by file as arguments).
What is the recommended way to point `myth -x ...` at a directory?

**Comment by b-mueller** [comment]
You should be able to do this:

```
myth -x Contracts/*.sol
```

Note that Mythril always uses the first contract as the entry point.

**Comment by ajsantander** [comment]
I that case, it'd be useful to be able to use a blob like:
```myth -x contracts/**/*.sol```

**Comment by b-mueller** [comment]
That would be quite difficult to implement and also counter-intuitive to use. Path meta-characters such as * are expanded by the shell, AFAIK you usually don't parse this stuff yourself.

**Comment by b-mueller** [comment]
Closing this as I think it isn's feasible.

**Comment by ajsantander** [comment]
What then would you recommend to run analysis on a multi-file project whose contracts are contained in an n-depth folder structure?

Does mythril require the files to be flattened into a single folder with all contracts at level 0? or even perhaps all contracts in a single file?

It may be unfeasible but it could be necessary too.

**Comment by b-mueller** [comment]
For now I'd recommend solving this with some bash magic, e.g. something like:

```
$ find contracts/*.sol | xargs myth -x
```

I'm also looking into Truffe / Github integration so Mythril can be used with actual projects. It would definitely be great to have but will still take some time.
