### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by infosec423** [b-mueller/mythril#34]
When I try to run 
python setup.py install
it returns these warnings:
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
no previously-included directories found matching 'docs\_build'
no previously-included directories found matching 'persistent\__pycache__'
error: Setup script exited with error: [WinError 2] The system cannot find the file specified

I am using Python 3.5
Any and all help is appreciated.

**Comment by b-mueller** [comment]
Hi @infosec423, seems to be an issue with your Python setuptools. Sorry I can't help you there, except for saying that you'll probably have an easier time if you set up a Linux VM for things like Mythril!
