### ISSUE TITLE
SVM cannot explore some paths

### ISSUE THREAD

**Issue by Raz0r** [b-mueller/mythril#39]
Function `playerRollDice` in contract https://etherscan.io/address/0xe6517b766e6ee07f91b517435ed855926bcb1aae#code ends with a REVERT, probably some conditions in modifiers are not resolved.  

![image](https://user-images.githubusercontent.com/150087/34338778-d2945c7e-e97c-11e7-9f7e-da70b6e05baa.png)

**Comment by b-mueller** [comment]
This should work as of Mythril 0.8.26:

```
$ myth --infura-mainnet -g ~/Desktop/test.html -a 0xe6517b766e6ee07f91b517435ed855926bcb1aae
```

However `playerRollDice` runs will be truncated at some point due to the symbolic execution depth limit. The default limit is 12. I have added a new command line argument so this can be changed:

```
$ myth --infura-mainnet -g ~/Desktop/test.html -a 0xe6517b766e6ee07f91b517435ed855926bcb1aae --max-depth 20
```
