### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by step21** [b-mueller/mythril#4]
Hi, nice to see this project. For more general analysis, I was investigating https://github.com/alex-miller-0/Ethereum_Blockchain_Parser before. I was also thinking about trying to port it to ipc, I think it should def be faster. Alternatively, maybe some parallelization could also speed things up or writing things to an intermediary db like for example the above project is doing (instead of one big file like mythril seems to be doing, thought they import all blocks to mongodb). (not sure if that is actually faster, but at least more convenient once imported)
I'll see what I can make of mythril, maybe if I use it I can help to make it use ipc or similar optimizations.

**Comment by b-mueller** [comment]
Hi @step21, there's definitely a lot of potential for improving the syncing. The best way would be to extract the state from Geth's LevelDB directly, but this requires some research on how that db is structured.

There's lots of other ideas also - some kind of incremental sync would be awesome, etc. I am currently not planning on investing too much effort on the syncing / exploration part though - for my purposes its enough to re-sync once a week or so.  I'm too excited about adding the symbolic VM and vulnerability detection capabilities :)

You would be very welcome to contribute!

PS. For storage I am currently using [persistent](https://pypi.python.org/pypi/persistent) which is super convenient from a coding perspective, but doesn't allow for parallelization. It also seems to be not very efficient in terms of HD usage.
