### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by postables** [b-mueller/mythril#40]
Pulled the repository from github and ran `python3.6 setup.py install`

Got the following error:

> Installed /usr/lib/python3.6/site-packages/ZODB-5.3.0-py3.6.egg
> Searching for ethereum>=2.0.4
> Reading https://pypi.python.org/simple/ethereum/
> Downloading https://pypi.python.org/packages/3f/09/4147180567abc6364d68a1620d50f81dd313765297065efcc9b42029c5bd/ethereum-2.2.0.tar.gz#md5=7a8b56336dedc3e91bb4442aae028cb7
> Best match: ethereum 2.2.0
> Processing ethereum-2.2.0.tar.gz
> Writing /tmp/easy_install-m923oopg/ethereum-2.2.0/setup.cfg
> Running ethereum-2.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-m923oopg/ethereum-2.2.0/egg-dist-tmp-aq7km6uq
> error: Setup script exited with error in ethereum setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed

**Comment by b-mueller** [comment]
Hi @postables, this seems to be an issue with the [PyEthereum](https://github.com/ethereum/pyethereum) package. Not related directly to Mythril, I suggest you create an issue in [their repo](https://github.com/ethereum/pyethereum/issues).
