### ISSUE TITLE
PR: using ipc as an option

### ISSUE THREAD

**Issue by step21** [b-mueller/mythril#6]
I made some changes to add an `--ipc` flag that uses ipc via web3.py.
Everything seems to work so far. Would you like/accept a pull request for that?

**Comment by step21** [comment]
One thing: I cannot really tell right now if it is faster with this method or not.

**Comment by b-mueller** [comment]
@step21 great! Yes, please do a pull request.

**Comment by b-mueller** [comment]
Thanks for the PR, I included it in the newest release!

**Comment by b-mueller** [comment]
Did you get around to testing whether IPC is faster than RPC? Might be worth making IPC the default setting.

**Comment by step21** [comment]
No, because I am not really sure how to test it. I would have thought ipc to be faster, because as far as I know even localhost http requests have some ip stack overhead etc but I cannot really tell. Would you use something like timeit() or something else?
